<?php /* Eine Zeile der Notizbuchliste. Steht zweimal im Baum: einmal für die
         sichtbaren Notizbücher, einmal für die aufgeklappten ausgeblendeten.
         Erwartet `notebook` aus dem umgebenden x-for. */ ?>
<div class="group relative flex items-center gap-1 rounded-md" :class="isActiveNotebook(notebook.id) ? 'notebook-item-active' : ''">
    <button type="button" @click="selectCollection('notebook', notebook.id)" @dragenter.prevent="setDropTargetNotebook(notebook.id)" @dragover.prevent="setDropTargetNotebook(notebook.id)" @drop.prevent="dropPageOnNotebook(notebook.id, $event)" class="notebook-item min-w-0 flex-1" :class="{ 'is-drop-target': isNotebookDropTarget(notebook.id) }"><span class="notebook-appearance shrink-0" :style="notebookIconStyle(notebook)" x-cloak><span x-show="!notebook.icon || notebook.icon === 'book-open'" x-icon="book-open:size-5"></span><span x-show="notebook.icon === 'folder'" x-icon="folder:size-5"></span><span x-show="notebook.icon === 'briefcase'" x-icon="briefcase:size-5"></span><span x-show="notebook.icon === 'house'" x-icon="house:size-5"></span><span x-show="notebook.icon === 'plane'" x-icon="plane:size-5"></span><span x-show="notebook.icon === 'heart'" x-icon="heart:size-5"></span><span x-show="notebook.icon === 'lightbulb'" x-icon="lightbulb:size-5"></span><span x-show="notebook.icon === 'laptop'" x-icon="laptop:size-5"></span><span x-show="notebook.icon === 'wrench'" x-icon="wrench:size-5"></span><span x-show="notebook.icon === 'utensils'" x-icon="utensils:size-5"></span><span x-show="notebook.icon === 'graduation-cap'" x-icon="graduation-cap:size-5"></span><span x-show="notebook.icon === 'star'" x-icon="star:size-5"></span></span><span class="truncate" x-text="notebook.name"></span><span x-show="notebook.is_shared" x-cloak class="shrink-0" style="color: var(--color-accent);" title="Geteiltes Notizbuch" x-icon="share-2"></span><span x-show="isNotebookDropTarget(notebook.id)" x-cloak class="ml-auto text-xs font-semibold">Hier ablegen</span><span x-show="!isNotebookDropTarget(notebook.id)" class="ml-auto text-xs" style="color: var(--color-text-muted);" x-text="notebook.page_count"></span></button>
    <button type="button" @click.stop="openNotebookMenu(notebook.id)" class="icon-action shrink-0" :aria-expanded="isNotebookMenuOpen(notebook.id)" aria-label="Notizbuchmenü öffnen" x-icon="more-horizontal"></button>
    <div x-show="isNotebookMenuOpen(notebook.id)" x-cloak @click.outside="closeNotebookMenu" @keydown.escape.window="closeNotebookMenu" class="absolute right-1 top-full z-30 mt-1 min-w-36 rounded-md border p-1" style="border-color: var(--color-border); background: var(--color-bg); box-shadow: var(--shadow-md);">
        <?php /* Teilen und Verlassen richten sich nach der Rolle: Der
                 Eigentümer verwaltet Teilnehmer, ein Teilnehmer kann nur die
                 eigene Freigabe aufgeben. */ ?>
        <button type="button" x-show="notebook.is_owner" @click="openNotebookShareDialog(notebook)" class="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><span x-icon="share-2"></span>Teilen</button>
        <button type="button" x-show="notebook.is_owner" @click="openRenameNotebookDialog(notebook)" class="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><span x-icon="pencil"></span>Umbenennen</button>
        <?php /* Ausblenden betrifft nur diese Liste - die Seiten bleiben
                 auffindbar und stehen weiter unter „Alle Notizen". */ ?>
        <button type="button" x-show="notebook.is_owner && !notebook.is_hidden" @click="setNotebookHidden(notebook, true)" class="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><span x-icon="eye-off"></span>Ausblenden</button>
        <button type="button" x-show="notebook.is_owner && notebook.is_hidden" x-cloak @click="setNotebookHidden(notebook, false)" class="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10"><span x-icon="eye"></span>Einblenden</button>
        <button type="button" x-show="notebook.is_owner" @click="deleteNotebook(notebook)" class="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10" style="color: var(--color-danger);"><span x-icon="trash"></span>Löschen</button>
        <button type="button" x-show="!notebook.is_owner" @click="leaveSharedNotebook(notebook)" class="flex w-full items-center gap-2 rounded px-2 py-2 text-left text-sm hover:bg-black/5 dark:hover:bg-white/10" style="color: var(--color-danger);"><span x-icon="log-out"></span>Verlassen</button>
    </div>
</div>
