import {
  ArrowUpRight,
  BetweenHorizontalStart,
  BetweenVerticalStart,
  BookOpen,
  Bold,
  BriefcaseBusiness,
  Camera,
  ChartColumn,
  Check,
  Circle,
  CircleDot,
  ClipboardPaste,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CloudOff,
  Code2,
  Cpu,
  Download,
  Eye,
  EyeOff,
  FileText,
  Folder,
  FolderKanban,
  GraduationCap,
  Heading1,
  Heading2,
  Highlighter,
  History,
  Home,
  House,
  Heart,
  Image,
  Info,
  Italic,
  Layers,
  KeyRound,
  Link,
  Lock,
  LockOpen,
  Laptop,
  Lightbulb,
  List,
  ListChecks,
  ListTodo,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  Mic,
  Minus,
  MoreHorizontal,
  MousePointer2,
  Paperclip,
  Pause,
  Pencil,
  Plane,
  Play,
  Plus,
  Printer,
  Quote,
  Redo2,
  Ruler,
  ScrollText,
  Search,
  Settings,
  Share2,
  Shield,
  Square,
  SquareCode,
  Star,
  Table,
  TableColumnsSplit,
  TableRowsSplit,
  Trash2,
  TriangleAlert,
  Type,
  Underline,
  Undo2,
  Upload,
  User,
  Users,
  Utensils,
  WandSparkles,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide';

const icons = {
  'arrow-up-right': ArrowUpRight,
  bold: Bold,
  'book-open': BookOpen,
  briefcase: BriefcaseBusiness,
  camera: Camera,
  'chart-column': ChartColumn,
  check: Check,
  circle: Circle,
  'circle-dot': CircleDot,
  'clipboard-paste': ClipboardPaste,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'cloud-off': CloudOff,
  code: Code2,
  cpu: Cpu,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  folder: Folder,
  'folder-kanban': FolderKanban,
  'graduation-cap': GraduationCap,
  'heading-1': Heading1,
  'heading-2': Heading2,
  highlighter: Highlighter,
  history: History,
  home: Home,
  house: House,
  heart: Heart,
  image: Image,
  info: Info,
  italic: Italic,
  layers: Layers,
  'key-round': KeyRound,
  link: Link,
  lock: Lock,
  'lock-open': LockOpen,
  laptop: Laptop,
  lightbulb: Lightbulb,
  list: List,
  'list-checks': ListChecks,
  'list-todo': ListTodo,
  'log-out': LogOut,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  menu: Menu,
  mic: Mic,
  minus: Minus,
  'more-horizontal': MoreHorizontal,
  'mouse-pointer-2': MousePointer2,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  plane: Plane,
  play: Play,
  plus: Plus,
  printer: Printer,
  quote: Quote,
  redo: Redo2,
  ruler: Ruler,
  'scroll-text': ScrollText,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  square: Square,
  'square-code': SquareCode,
  star: Star,
  table: Table,
  'table-add-col': BetweenVerticalStart,
  'table-add-row': BetweenHorizontalStart,
  'table-del-col': TableColumnsSplit,
  'table-del-row': TableRowsSplit,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  type: Type,
  underline: Underline,
  undo: Undo2,
  upload: Upload,
  user: User,
  users: Users,
  utensils: Utensils,
  'wand-sparkles': WandSparkles,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

function renderNode([tag, attributes, children]) {
  const attrs = Object.entries(attributes)
    .map(([key, value]) => `${key}="${value}"`)
    .join(' ');
  const content = (children || []).map(renderNode).join('');

  return `<${tag} ${attrs}>${content}</${tag}>`;
}

export function icon(name, className = 'size-4') {
  const iconNode = icons[name] || FileText;
  const [tag, attributes, children] = iconNode;

  return renderNode([
    tag,
    { ...attributes, class: className, 'aria-hidden': 'true' },
    children,
  ]);
}

/**
 * `x-icon="plus:size-8"` überschreibt die sonst feste 1rem-Größe (`size-4`) -
 * für einzelne, bewusst groß gesetzte Symbole wie den Leerzustand.
 */
export function renderIconDirective(el, expression) {
  const [name, className] = expression.replace(/["']/g, '').trim().split(':');
  el.innerHTML = icon(name, className || undefined);
}
